### ISSUE TITLE
Support for Last Day of Week and Last Day of Month?

### ISSUE THREAD

**Issue by rdehuyss** [asahaf/javacron#2]
Hi Ahmed,

first of all I would like to congratulate you - your javacron still is working great and very stable in JobRunr.

I have a feature request from JobRunr users - support for last day of week and last day of month. Is this something that would be difficult to add?

Thanks again, 
Ronald

**Comment by asahaf** [comment]
Hi Ronald,

I'm very happy to hear that. I'll look at it and get back to you 

Thanks

**Comment by rdehuyss** [comment]
Awesome, thanks!

**Comment by asahaf** [comment]
I assume you want to have last day of the week and last day of the month, both conditions to be met, right?. Because last day of the week is easy to specify using the last segment. e.g 
`0 0 * * 6` if you want the schedule to be at the beginning of the specified day or 
`0 0 * * 0` if you want the schedule to be at the end of the specified day. 
For both conditions, we can make it with this pattern:
 `0 0 1 * 0`, assuming you want to to schedule it at the end of the day (when the specified day finishes). 
would this that be a good solution?

**Comment by rdehuyss** [comment]
Hi @asahaf , I think we're talking about different stuff (but I must admit that my Cron knowledge is probably way less than yours).

I'm talking about this: https://en.wikipedia.org/wiki/Cron#Non-standard_characters

> L
'L' stands for "last". When used in the day-of-week field, it allows specifying constructs such as "the last Friday" ("5L") of a given month. In the day-of-month field, it specifies the last day of the month.
W
The 'W' character is allowed for the day-of-month field. This character is used to specify the weekday (Monday-Friday) nearest the given day. As an example, if "15W" is specified as the value for the day-of-month field, the meaning is: "the nearest weekday to the 15th of the month." So, if the 15th is a Saturday, the trigger fires on Friday the 14th. If the 15th is a Sunday, the trigger fires on Monday the 16th. If the 15th is a Tuesday, then it fires on Tuesday the 15th. However, if "1W" is specified as the value for day-of-month, and the 1st is a Saturday, the trigger fires on Monday the 3rd, as it does not 'jump' over the boundary of a month's days. The 'W' character can be specified only when the day-of-month is a single day, not a range or list of days.

**Comment by asahaf** [comment]
oh, I see what you mean now. it would be nice to have, I'll look at it

**Comment by asahaf** [comment]
@[rdehuyss](https://github.com/rdehuyss) The last day of a month is merged into master (v1.3.0)

**Comment by rdehuyss** [comment]
You're the best!! I'll certainly mention you in the release notes for the next JobRunr version. Thank you so much for you help!

**Comment by asahaf** [comment]
Hi,

I’m very happy to help :)

Best regards,
Ahmed
